version: '3'
services:
  polybot:
    build: ./polybot
    # Add necessary environment variables
    environment:
      - TELEGRAM_API_TOKEN=<your_telegram_api_token>
    # Add any other configuration options

  yolo5:
    build: ./yolo5
    # Add necessary environment variables
    # Link yolo5 with mongo and polybot
    depends_on:
      - mongo
      - polybot
    # Add any other configuration options

  mongo:
    image: mongo
    # Add necessary environment variables for MongoDB setup
    volumes:
      - ./mongo/data:/data/db
    # Add any other configuration options
